In [1]:
import numpy as np

# Define matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Print matrices for reference
print("Matrix A:\n", a_ndarray)
print("Matrix B:\n", b_ndarray)


Matrix A:
 [[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
Matrix B:
 [[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


In [2]:
# Compute matrix product using NumPy
c_ndarray = np.matmul(a_ndarray, b_ndarray)  # Alternatively: a_ndarray @ b_ndarray
print("Matrix Product using NumPy:\n", c_ndarray)


Matrix Product using NumPy:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [3]:
# Compute one element C[0,0] manually
c_00 = a_ndarray[0, 0] * b_ndarray[0, 0] + a_ndarray[0, 1] * b_ndarray[1, 0] + a_ndarray[0, 2] * b_ndarray[2, 0]
print("Manually Computed C[0,0]:", c_00)


Manually Computed C[0,0]: 6


In [4]:
def matrix_multiply(A, B):
    # Get the dimensions of A and B
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Check if multiplication is possible
    if cols_A != rows_B:
        raise ValueError("Matrix multiplication not defined: Number of columns of A must equal number of rows of B.")

    # Create an output matrix filled with zeros
    C = np.zeros((rows_A, cols_B))

    # Compute each element C[i, j]
    for i in range(rows_A):
        for j in range(cols_B):
            C[i, j] = sum(A[i, k] * B[k, j] for k in range(cols_A))

    return C

# Compute matrix product using the function
c_manual = matrix_multiply(a_ndarray, b_ndarray)
print("Matrix Product using Manual Implementation:\n", c_manual)


Matrix Product using Manual Implementation:
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [6]:
def matrix_multiply_safe(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    if cols_A != rows_B:
        print(f"Matrix multiplication not possible: A has {cols_A} columns, but B has {rows_B} rows.")
        return None  # Return None to indicate failure

    C = np.zeros((rows_A, cols_B))

    for i in range(rows_A):
        for j in range(cols_B):
            C[i, j] = sum(A[i, k] * B[k, j] for k in range(cols_A))

    return C

# Test with invalid matrices
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

c_invalid = matrix_multiply_safe(d_ndarray, e_ndarray)  # Should print an error message


Matrix multiplication not possible: A has 3 columns, but B has 2 rows.


In [7]:
# Transpose matrix E
e_transposed = e_ndarray.T

# Compute valid multiplication
c_valid = matrix_multiply_safe(d_ndarray, e_transposed)
print("Matrix Product after Transposing E:\n", c_valid)


Matrix Product after Transposing E:
 [[ 46.  -4.]
 [-34.  73.]]
